version: '3.8'

services:
  api:
    build: .
    container_name: fitapp_api
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:Nasigoreng123%40@db:5432/fitapp?schema=public
      - JWT_SECRET=Nasigoreng123@
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: fitapp_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: GANTI_PASSWORD_INI
      POSTGRES_DB: fitapp
    volumes:
      - fitapp_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fitapp"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  fitapp_pgdata:
